google_analytics_code:                              # Enter your `UA-XXXXXXXX-X` code here
home_url:                                           # http://getgrav.org
github:
    position: top                                   # top | bottom | off
    tree: https://github.com/jdubuisson/mfz-ra-rules/blob/master/
    commits: https://github.com/jdubuisson/mfz-ra-rules/commits/master/
