title: Rules for Mobile Frame Zero : Rapid Attack
author:
  name: Joe Bloggs
  email: 'joe@test.com'
metadata:
    description: 'Build your mobile frames of LEGO® or other building toys and fight for control of the tabletop!'

